{{- if .Values.db.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: traffic-db
spec:
  type: {{ .Values.db.serviceType | default "ClusterIP" }}
  {{- if and (eq (.Values.db.serviceType | default "ClusterIP") "LoadBalancer") .Values.db.loadBalancerIP }}
  loadBalancerIP: {{ .Values.db.loadBalancerIP }}
  {{- end }}
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: traffic-db
{{- end }}
