# On-Prem 클러스터 전용 Override Values
# Umbrella Chart (Subchart) 구조에 맞게 작성

ingressRule:
  namespace: "jit-hub"
  host: "leechs.shop"

gateway:
  replicaCount: 1
  image:
    repository: "changsiuuuu/jit-hub-gateway"
    tag: "latest"

auth:
  replicaCount: 1
  image:
    repository: "changsiuuuu/auth-service"
    tag: "latest"

weather:
  replicaCount: 1
  image:
    repository: "changsiuuuu/weather-service"
    tag: "latest"

traffic:
  replicaCount: 1
  image:
    repository: "changsiuuuu/traffic-service"
    tag: "latest"

tourist:
  replicaCount: 1
  image:
    repository: "changsiuuuu/tourist-service"
    tag: "latest"
